JulienFerez/courslmbricolage

- pages/store.tsx
- styles/globals.css
Ajout de l'authentification lorsqu'on clic pour réserver un cours
But : limiter l'accès à la page à un utilisateur authentifier
Résultat : l'utilisateur est invité à se connecter avant d'accéder à la page des catégories (store) et il est bien renvoyé vers cette page
Page catégorie : en cours de construction avec un tableau et des images qui renvoie vers une autre page
(+ Fix bug)
> MAJ auth0 + store (sans bug)

- pages/api/updateDB-Test.ts
- pages/createClass-Test.tsx
- src/utils/database.ts
- Création d'une api route
- Création d'une page pour réserver un créneau pour faire cours
> Started API route (WIP)

- package.json
- pages/onlinestore/[category]/[tuto]/index.tsx
- pages/onlinestore/[category]/index.tsx
- pages/onlinestore/index.tsx
- styles/globals.css
- yarn.lock
Reste à insérer du contenu dans la DB
> Parcours tuto finish

- .eslintrc.json
- pages/api/updateDB-Test.ts
- pages/createClass-Test.tsx
creation de rdv et mise a jjour de la db
ajout des fichiers :
- updateDB-Test.tsx
- createClass-Test.tsx
> creation de rdv et mise a jjour de la db

- pages/api/createUser.ts
- pages/form.tsx
- Création d'une route api pour update la DB users
- Création d'un Form pour les nouveaux utilisateurs
> Create form for new users (WIP)

- pages/store/[store_slug]/[slug_details]/index.tsx
- pages/validation.tsx
- styles/globals.css
> affichage des créneaux + formulaire

- .eslintrc.json
- pages/form.tsx
- pages/index.tsx
page form (back) + redirection vers le cours (version1) + mise a jour db users
> pge form (back) + redirection vers le cours (version1) + mise a jour db

- pages/cartStore.tsx
- pages/store/index.tsx
> Recap utilisateur dans le panier

- pages/onlinestore/[category]/[tuto]/index.tsx
- pages/onlinestore/[category]/index.tsx
> fix problem redirect bouton tuto

- pages/api/updateWishTeacher.ts
- pages/profil.tsx
-Ajout de la page form sur le profil de l'utilisateur pour demander à devenir prof
-Création API pour update la clé wishTeacher dans db
> ajout form sur la page profil pour demande prof

- pages/form.tsx
- pages/store/[store_slug]/index.tsx
- pages/store/index.tsx
- styles/layout.css
Changement CSS page Button goOnStore avec phrase de redirection clicable
Ajout className dans fichier css
> Changement CSS page button goOnStore avec className dans css

- components/Layout.tsx
- pages/index.tsx
- pages/onlinestore/index.tsx
- pages/store/index.tsx
- styles/globals.css
CSS Home page : reste à finir les photos, description, espace entre les photos. 
CSS Category Tuto + Category Cours en magasin
> CSS Pages Category Tuto + CoursMag + CSS home PAge

- components/Layout.tsx
- pages/onlinestore/[category]/index.tsx
- styles/globals.css
ajoute style CSS sur la page catégorie tuto online
> add CSS page online category

- pages/store/[store_slug]/index.tsx
> différents cours magasin OK

- pages/form.tsx
- styles/globals.css
> css Page Form

- pages/onlinestore/[category]/[tuto]/index.tsx
- pages/store/[store_slug]/[slug_details]/index.tsx
- styles/globals.css
> CSS Slot/tuto/cours OK

- pages/api/updateCart.ts
- pages/cartStore.tsx
- pages/profil.tsx
- pages/store/[store_slug]/[slug_details]/index.tsx
- styles/globals.css
> Add css for the cart

- components/Layout.tsx
- pages/cartStore.tsx
- pages/contact.tsx
- pages/form.tsx
- pages/index.tsx
- pages/onlinestore/[category]/[tuto]/index.tsx
- pages/onlinestore/[category]/index.tsx
- pages/onlinestore/index.tsx
- pages/profil.tsx
- pages/profilProf.tsx
- pages/store/[store_slug]/[slug_details]/index.tsx
- pages/store/[store_slug]/index.tsx
- pages/store/index.tsx
- Ajoute un titre dynamiquement sur la layout
> Add title to the layout.

- components/Layout.tsx
- pages/cartStore.tsx
- pages/contact.tsx
- pages/createClass.tsx
- pages/form.tsx
- pages/index.tsx
- pages/profil.tsx
- pages/store/index.tsx
afficher le nom sur la Navbar 
layout dynamique
> Profil condition

- pages/createClass.tsx
- styles/globals.css
> css Page createClass

- pages/cartStore.tsx
- styles/globals.css
- styles/layout.css
Changement chemin image navbar Test
Ajout code promo dans panier
Modification de css
> changement accès image navbar + ajouit code promo + css

- components/Layout.tsx
- pages/cartStore.tsx
- pages/contact.tsx
- pages/index.tsx
- pages/onlinestore/[category]/[tuto]/index.tsx
- pages/store/[store_slug]/[slug_details]/index.tsx
- pages/store/[store_slug]/index.tsx
- styles/globals.css
Fini les derniers détails sur css (manque la page profil)
> Polish the css

- pages/api/createClass.ts
- pages/createClass.tsx
- pages/index.tsx
- pages/profil.tsx
- styles/globals.css
- Fini le css du profil
- fix la page "createClass"
> CSS profil + fix createClass

- pages/index.tsx
- styles/globals.css
Ajoute des détails de css sur la home page
> Add css to the main buttons of home page

- styles/globals.css
fix bug css (scroll creenaux) page profil user
> fix bug css

- pages/profil.tsx
> Fix bug profil user
